server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.foldyang.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: back1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka56080.com:56080/eureka/,http://eureka56081.com:56081/eureka/,http://eureka56082.com:56082/eureka/
  instance:
    instance-id: back1_8001 #eureka在注册表中显示的名称
    prefer-ip-address: true #显示ip

info:
  app.name: back1
  company.name: www.foldyang.com
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"