server:
  port: 82

feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka56080.com:56080/eureka/,http://eureka56081.com:56081/eureka/,http://eureka56082.com:56082/eureka/